# Generated by Django 3.2 on 2021-06-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='status',
        ),
    ]
