# Generated by Django 3.2 on 2021-06-18 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210616_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 6, 18)),
        ),
    ]
